Upgrade ORC version to 1.6.13 to get a fix for ORC-1065
On some occasions PXF fails with the following error if the query
against a Hive ORC table is performed from the same session. The first
query succeeds, but the second fails. It seems it is related to ORC-1065
that is fixed in ORC 1.6.13.

```
java.lang.RuntimeException: ORC split generation failed with exception: 28325
```

The error occurs when Hive use the ETL split strategy -- either
expressly configured or selected when using the hybrid strategy which
depends on the number and average size of the ORC files being read (see
org.apache.hadoop.hive.ql.io.orc.OrcInputFormat for details).

An integration test is added that generates a large data set that is
stored in a single ORC file that is then read by PXF using the Hive ORC
profile. This is intended to cause OrcInputFormat.determineSplitStrategy
to select the ETL split strategy when using the default configuration of
HYBRID. When the ETL split strategy is used, a bug in the ORC library is
encountered with caching file footers (see [ORC-1065][] for more
details.)

[ORC-1065]: https://issues.apache.org/jira/browse/ORC-1065

Authored-by: Bradford D. Boyle <bradfordb@vmware.com>